### ISSUE TITLE
"follow" links 

### ISSUE THREAD

**Issue by dams57k** [BuildFire/socialPlugin#26]
Hello,

I have some questions about the Social Plugin. There are links that allow users to follow threads. When I click on this link for a thread, does that store this information somewhere? If yes, where ?

I am asking that as I want to allow the users to keep track of what they follow, and to be able to retrieve this info through a button. I am developing a user profile page (as a plugin), and I want to sync the follow updates on the Social wall to the user profile. What is a good way to do that, and in particular, which data type should I use that is transversal to different plugins?

Thank you,
Damien

**Comment by DanielHindi** [comment]
For you to be able to store user data you need the UserData feature that is coming out this month. Keep an eye out for it on our twitter account https://twitter.com/BuildfireDev

**Comment by dams57k** [comment]
Hi Daniel,

Thanks for the update, I ll check the UserData release announce on Twitter.

   1.

   To be sure I fully understand, this UserData feature (is it a plugin ?)
   allows me to:


   -

   Read AND write for the widget side
   -

   Edit it? Can I add remove fields?




   1.

   Besides, I saw you video on porting a project to the Buildfire SDK. My
   question is: can port an ionic/Cordova project, or is there something there
   that prevents its porting? I would like to port the cordova ContactList
   plugin.

Thanks,

Damien

**Comment by DanielHindi** [comment]
1. User Data is an api in buildfire.js its out in beta
https://github.com/BuildFire/sdk/wiki/User-Data:-Save-user-data-from-the-widget
You can use it within your plugin. You can read and write user data in the widget/app

2. Any JS framework should work just fine in our system

3. Contact List API is also on its way

**Comment by dams57k** [comment]
Hi Daniel,

OK, I did not understand hy you use the term FEATURE and not PLUGIN for the
userData. What I also need is to change the input fields in the user data
template. I understand it is not a plugin as it involves sharing
information between several plugins. However, the template must be
somewhere.
How can I access the template of the user profile page ?

Thanks.
Damien

**Comment by DanielHindi** [comment]
I think you may be confusing User Profile with UserData.
The user profile is a core authentication feature that allows users to register to an app and maintain their profile

UserData is a new feature like DataStore. Its a database for user driven data. it can be anything. its completely independent from user profile. However, you may create your own user profile using UserData

I hope this helps

**Comment by dams57k** [comment]
Indeed, I did confuse User Profile with UserData.

My aim is to come with a User Profile with customized fields. From what I
have seen, there a User Profile in buildfire, and I would be happy to use
it provided I can modify some of the input fields. That is purely a front
end approach, independent of worrying about data persistency.

What I do not see is, in the social wall Plugin when I click on the author
name of a post, how to route to the User Profile I would create with the
author’s information . In the thread.html file of the social plugin/widget,
the routing is being done triggering “Thread.buildfire.auth.openProfile”. I
have no idea how this command routes to the UserProfile.

I see two possible ways to overcome this issue.

   1.

   Either I can acces the template being loading when
   “Thread.buildfire.auth.openProfile” is called. And then modify the labels
   of the form.
   2.

   I create my own User Profile, but I find a way to route to it when
   “Thread.buildfire.auth.openProfile” is called. For that purpose, will it
   work if  I use the command written in the GridLayoutPlugin to route
   towards a particular plugin : “buildfire.navigation.navigateTo(…)” ?



   This is critical for us, and we cannot publish until that issue is
   solved.



Thanks,

Damien

**Comment by DanielHindi** [comment]
I assume you are forking the social plugin. If so, you can hijack the openProfile call and make it go into a subsection in your forked plugin that displays the user profile in any which way you want. You could have a shadow profile thats completely yours

**Comment by dams57k** [comment]
Yes, I am forking the social wall Plugin.

I see… so I will call a function internal to the socialwall plugin instead
of OpenProfile call . For that I will need to have the template of my
shadow user profile within the social wall profile. Then I can populate the
info of whoever from the buildfire.userdata feature. Am I correct ?

Thanks,

Damien

**Comment by DanielHindi** [comment]
you got it

On Thu, Mar 17, 2016 at 1:59 PM, dams57k <notifications@github.com> wrote:

> Yes, I am forking the social wall Plugin.
>
> I see… so I will call a function internal to the socialwall plugin instead
> of OpenProfile call . For that I will need to have the template of my
> shadow user profile within the social wall profile. Then I can populate the
> info of whoever from the buildfire.userdata feature. Am I correct ?
>
> Thanks,
>
> Damien
>
> On Thu, Mar 17, 2016 at 12:50 PM, Daniel Hindi <notifications@github.com>
> wrote:
>
> > I assume you are forking the social plugin. If so, you can hijack the
> > openProfile call and make it go into a subsection in your forked plugin
> > that displays the user profile in any which way you want. You could have
> a
> > shadow profile thats completely yours
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/BuildFire/socialPlugin/issues/26#issuecomment-198055087
> >
>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/BuildFire/socialPlugin/issues/26#issuecomment-198080277>
>



-- 

*Daniel Hindi | Chief Technology Officer and CEO*

*Phone:* 1-619-786-0778

*Skype: *daniel_hindi

*Website:* MadainCorp.com

**Comment by dams57k** [comment]
Great, thanks for your help !
Damien

**Comment by dams57k** [comment]
Hi Daniel,

Still with the User Profile issue, the in-built profile is automatically
present in the side menu once logged on. However, as I mentioned I need to
create my own User Profile with customized fields. How can I route this
side menu tab my own user profile plugin ?

Thanks,
Damien

**Comment by DanielHindi** [comment]
Your best bet will be to hide it we are releasing settings for that soon. let me get back to you on a time line

**Comment by dams57k** [comment]
Thanks !
Damien

**Comment by DanielHindi** [comment]
Update: String Resources were released.
![image](https://cloud.githubusercontent.com/assets/492189/14614825/b75aca3e-0557-11e6-8566-3187ebd91e4a.png)
